// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAptH01TliCoUvQ4xcX5QAlwUmTa-vaTr0',
    appId: '1:230890667286:web:e4e6db2b8e2044e2dc6437',
    messagingSenderId: '230890667286',
    projectId: 'appswingers-5c5cc',
    authDomain: 'appswingers-5c5cc.firebaseapp.com',
    storageBucket: 'appswingers-5c5cc.firebasestorage.app',
    measurementId: 'G-7KS40RR0VQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu_cReaQlQcBNyT8gOQ_p1gaMeJbK0JHY',
    appId: '1:230890667286:android:d6694dcc73f2e2c0dc6437',
    messagingSenderId: '230890667286',
    projectId: 'appswingers-5c5cc',
    storageBucket: 'appswingers-5c5cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIeKDvz5czf3jIZG-Et_X62Pdl-Ov5U0w',
    appId: '1:230890667286:ios:b5304b8848589c8cdc6437',
    messagingSenderId: '230890667286',
    projectId: 'appswingers-5c5cc',
    storageBucket: 'appswingers-5c5cc.firebasestorage.app',
    iosBundleId: 'com.example.appswingger',
  );
}
